### ISSUE TITLE
ns doesn't exist.

### ISSUE THREAD

**Issue by Siba94** [mmucklo/DtcQueueBundle#39]
I am using **4.0** version of this bundle and whenever I run console command **dtc:queue:count**, it gives me a exception -> **ns doesn't exist.**

**Comment by mmucklo** [comment]
I'll take a look

**Comment by mmucklo** [comment]
May have fixed it in the PR, but I'll have to check it later...signing off for now.

**Comment by mmucklo** [comment]
Please check if the issue is fixed in 4.1.0

**Comment by mmucklo** [comment]
@Siba94 did the fix I did work?

**Comment by Siba94** [comment]
checking it right now. i'll let you know about it.

**Comment by Siba94** [comment]
No, still have the same issue.
I am following the documentation as mentioned for symfony3
Steps are :
1- Composer require.
2- Register the bundle in AppKernel.
3- Set up config.yml for MongoDB ODM
4- Set up routes in routing.yml
5- Set up security.yml to allow admins.
and then while doing dtc:queue:count it gives exception **ns doesn't exist**.

**Comment by mmucklo** [comment]
@Siba94 - Oh I know what's going on - the database and collection don't exist yet in Mongo.

If you create then run a job, it should fix that, however I should see if there's a way to catch that before executing the count command.

**Comment by Siba94** [comment]
Thanks a lot. @mmucklo

**Comment by Siba94** [comment]
@mmucklo Let me check. I will update you.

**Comment by mmucklo** [comment]
@Siba94 Ok, thanks, let me know...

**Comment by Siba94** [comment]
@mmucklo still have the same issue. I had a job collection also as mentioned by you before running the count command create job first but when I run the **count** command it still generates the same exception.
 I can see the jobs in waiting queue by following /dtc_queue/jobs route.
![selection_018](https://user-images.githubusercontent.com/12645991/35232969-da5efc64-ffc2-11e7-82c0-6c21a552402e.png)
![selection_019](https://user-images.githubusercontent.com/12645991/35233193-6843af48-ffc3-11e7-8df3-2f7ee0d8aa46.png)

**Comment by mmucklo** [comment]
Ok, let me check it out.

**Comment by mmucklo** [comment]
@Siba94,

I think I got it this time in 4.3.1 - yours is responding "ns doesn't exist" whereas mine was responding "namespace does not exist".

The code should now catch both.

Let me know,

--Matt

**Comment by mmucklo** [comment]
@Siba94 - did 4.3.1 fix the issue for you?

**Comment by Siba94** [comment]
@mmucklo let me check it

**Comment by mmucklo** [comment]
@Siba94 - ok thanks once again...

**Comment by Siba94** [comment]
Thanks a lot @mmucklo it's working perfectly.

**Comment by mmucklo** [comment]
@Siba94 - good news thanks.  Closing the issue.
